"""empty message

Revision ID: feb98fe5d170
Revises: 
Create Date: 2022-03-31 20:44:48.821756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb98fe5d170'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokedex')
    op.drop_table('pokemon')
    op.add_column('user', sa.Column('apitoken', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apitoken')
    op.create_table('pokemon',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pokemon_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('pokemon_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('img_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('ability1', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('ability2', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pokemon_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pokedex',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name='pokedex_pokemon_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='pokedex_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pokedex_pkey')
    )
    # ### end Alembic commands ###
